import requests
from bs4 import BeautifulSoup


def month_convert(number: str):
    month = {
        '1': 'Ene',
        '2': 'Feb',
        '3': 'Mar',
        '4': 'Abr',
        '5': 'Mayo',
        '6': 'Jun',
        '7': 'Jul',
        '8': 'Ago',
        '9': 'Sep',
        '10': 'Oct',
        '11': 'Nov',
        '12': 'Dic',
    }
    return month[number]


def tasa_bancos(day: str, month: str, year: str):
    fecha = day + ' ' + month_convert(month) + ' ' + year
    payload = {
        'field_fecha_del_indicador_value[min][date]': fecha,
        'field_fecha_del_indicador_value[max][date]': fecha,
        'view_name': 'tasas_sistema_bancario_full',
        'view_display_id': 'page',
        'view_args': '',
        'view_path': 'tasas-informativas-sistema-bancario',
        'view_base_path': 'tasas-informativas-sistema-bancario',
        'view_dom_id': '0fc85192abaedd6c88bb33f354e79451',
        'pager_element': '0',
        'ajax_html_ids[]': 'skip-link',
        'ajax_html_ids[]': 'banner',
        'ajax_html_ids[]': 'block-search-form',
        'ajax_html_ids[]': 'search-block-form',
        'ajax_html_ids[]': 'edit-search-block-form--2',
        'ajax_html_ids[]': 'edit-actions',
        'ajax_html_ids[]': 'edit-submit',
        'ajax_html_ids[]': 'navbar',
        'ajax_html_ids[]': 'top-xs',
        'ajax_html_ids[]': 'button-search-responsive',
        'ajax_html_ids[]': 'search',
        'ajax_html_ids[]': 'search-form',
        'ajax_html_ids[]': 'edit-basic',
        'ajax_html_ids[]': 'edit-keys',
        'ajax_html_ids[]': 'edit-submit--2',
        'ajax_html_ids[]': 'navbar-collapse',
        'ajax_html_ids[]': 'page-header',
        'ajax_html_ids[]': 'main-content',
        'ajax_html_ids[]': 'block-system-main',
        'ajax_html_ids[]': 'views-exposed-form-tasas-sistema-bancario-full-page',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-wrapper',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-min-wrapper',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-min-inside-wrapper',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-min',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-min-datepicker-popup-0',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-max-wrapper',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-max-inside-wrapper',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-max',
        'ajax_html_ids[]': 'edit-field-fecha-del -indicador-value-max-datepicker-popup-0',
        'ajax_html_ids[]': 'edit-submit-tasas-sistema-bancario-full',
        'ajax_html_ids[]': 'sidebar_first',
        'ajax_html_ids[]': 'block-views-47bbee0af9473fcf0d6df64198f4df6b',
        'ajax_html_ids[]': 'titulo1',
        'ajax_html_ids[]': 'tcr',
        'ajax_html_ids[]': 'euro',
        'ajax_html_ids[]': 'yuan',
        'ajax_html_ids[]': 'lira',
        'ajax_html_ids[]': 'rublo',
        'ajax_html_ids[]': 'dolar',
        'ajax_html_ids[]': 'block-views-tasas-sistema-bancario-block',
        'ajax_html_ids[]': 'block-views-banners-servicio-block',
        'ajax_html_ids[]': 'block-footer-sitemap-footer-sitemap',
        'ajax_html_ids[]': 'footer-sitemap',
        'ajax_html_ids[]': 'block-social-media-links-social-media-links',
        'ajax_html_ids[]': 'cboxOverlay',
        'ajax_html_ids[]': 'colorbox',
        'ajax_html_ids[]': 'cboxWrapper',
        'ajax_html_ids[]': 'cboxTopLeft',
        'ajax_html_ids[]': 'cboxTopCenter',
        'ajax_html_ids[]': 'cboxTopRight',
        'ajax_html_ids[]': 'cboxMiddleLeft',
        'ajax_html_ids[]': 'cboxContent',
        'ajax_html_ids[]': 'cboxTitle',
        'ajax_html_ids[]': 'cboxCurrent',
        'ajax_html_ids[]': 'cboxPrevious',
        'ajax_html_ids[]': 'cboxNext',
        'ajax_html_ids[]': 'cboxSlideshow',
        'ajax_html_ids[]': 'cboxLoadingOverlay',
        'ajax_html_ids[]': 'cboxLoadingGraphic',
        'ajax_html_ids[]': 'cboxMiddleRight',
        'ajax_html_ids[]': 'cboxBottomLeft',
        'ajax_html_ids[]': 'cboxBottomCenter',
        'ajax_html_ids[]': 'cboxBottomRight',
        'ajax_html_ids[]': 'ui-datepicker-div',
        'ajax_page_state[theme]': 'bcv_ultimate',
        'ajax_page_state[theme_token]': 'EeJzR7epgcG8t6PrpJxox0TASe_Xjps7utdQpPF4CLY',
        'ajax_page_state[css][modules/system/system.base.css]': 1,
        'ajax_page_state[css][misc/ui/jquery.ui.core.css]': 1,
        'ajax_page_state[css][misc/ui/jquery.ui.theme.css]': 1,
        'ajax_page_state[css][misc/ui/jquery.ui.datepicker.css]': 1,
        'ajax_page_state[css][sites/all/modules/date/date_popup/themes/jquery.timeentry.css]': 1,
        'ajax_page_state[css][sites/all/modules/date/date_api/date.css]': 1,
        'ajax_page_state[css][sites/all/modules/date/date_popup/themes/datepicker.1.7.css]': 1,
        'ajax_page_state[css][modules/field/theme/field.css]': 1,
        'ajax_page_state[css][sites/all/modules/footer_sitemap/footer_sitemap.css]': 1,
        'ajax_page_state[css][modules/node/node.css]': 1,
        'ajax_page_state[css][sites/all/modules/youtube/css/youtube.css]': 1,
        'ajax_page_state[css][sites/all/modules/views/css/views.css]': 1,
        'ajax_page_state[css][sites/all/modules/ckeditor/css/ckeditor.css]': 1,
        'ajax_page_state[css][sites/all/modules/colorbox/styles/default/colorbox_style.css]': 1,
        'ajax_page_state[css][sites/all/modules/ctools/css/ctools.css]': 1,
        'ajax_page_state[css][sites/all/modules/context/dhtml_menu/dhtml_menu.css]': 1,
        'ajax_page_state[css][sites/all/modules/dynamic_banner/css/banner.css]': 1,
        'ajax_page_state[css][sites/all/modules/social_media_links/social_media_links.css]': 1,
        'ajax_page_state[css][sites/all/libraries/superfish/css/superfish.css]': 1,
        'ajax_page_state[css][sites/all/libraries/superfish/css/superfish-smallscreen.css]': 1,
        'ajax_page_state[css][sites/all/libraries/superfish/style/simple/simple.css]': 1,
        'ajax_page_state[css][sites/all/themes/bcv_ultimate/css/style.css]': 1,
        'ajax_page_state[js][0]': 1,
        'ajax_page_state[js][1]': 1,
        'ajax_page_state[js][2]': 1,
        'ajax_page_state[js][3]': 1,
        'ajax_page_state[js][sites/all/themes/bootstrap/js/bootstrap.js]': 1,
        'ajax_page_state[js][//code.jquery.com/jquery-1.10.2.min.js]': 1,
        'ajax_page_state[js][misc/jquery.once.js]': 1,
        'ajax_page_state[js][misc/drupal.js]': 1,
        'ajax_page_state[js][//code.jquery.com/ui/1.10.2/jquery-ui.min.js]': 1,
        'ajax_page_state[js][sites/all/modules/jquery_update/replace/ui/external/jquery.cookie.js]': 1,
        'ajax_page_state[js][sites/all/modules/jquery_update/replace/misc/jquery.form.min.js]': 1,
        'ajax_page_state[js][modules/locale/locale.datepicker.js]': 1,
        'ajax_page_state[js][sites/all/modules/date/date_popup/jquery.timeentry.pack.js]': 1,
        'ajax_page_state[js][misc/ajax.js]': 1,
        'ajax_page_state[js][sites/all/modules/jquery_update/js/jquery_update.js]': 1,
        'ajax_page_state[js][public://languages/es_Wyx0mRNwGoYV99FpTUFhq2hYKJFRPI-5w_dSK9tmg-g.js]': 1,
        'ajax_page_state[js][sites/all/libraries/colorbox/jquery.colorbox-min.js]': 1,
        'ajax_page_state[js][sites/all/modules/colorbox/js/colorbox.js]': 1,
        'ajax_page_state[js][sites/all/modules/colorbox/styles/default/colorbox_style.js]': 1,
        'ajax_page_state[js][sites/all/modules/context/dhtml_menu/dhtml_menu.js]': 1,
        'ajax_page_state[js][sites/all/modules/dynamic_banner/js/banner.js]': 1,
        'ajax_page_state[js][sites/all/modules/date/date_popup/date_popup.js]': 1,
        'ajax_page_state[js][sites/all/modules/views/js/base.js]': 1,
        'ajax_page_state[js][sites/all/themes/bootstrap/js/misc/_progress.js]': 1,
        'ajax_page_state[js][sites/all/modules/views/js/ajax_view.js]': 1,
        'ajax_page_state[js][sites/all/modules/google_analytics/googleanalytics.js]': 1,
        'ajax_page_state[js][sites/all/libraries/superfish/jquery.hoverIntent.minified.js]': 1,
        'ajax_page_state[js][sites/all/libraries/superfish/sfsmallscreen.js]': 1,
        'ajax_page_state[js][sites/all/libraries/superfish/supposition.js]': 1,
        'ajax_page_state[js][sites/all/libraries/superfish/superfish.js]': 1,
        'ajax_page_state[js][sites/all/libraries/superfish/supersubs.js]': 1,
        'ajax_page_state[js][sites/all/modules/superfish/superfish.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/affix.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/alert.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/button.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/carousel.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/collapse.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/dropdown.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/modal.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/tooltip.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/popover.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/scrollspy.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/tab.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/bootstrap/js/transition.js]': 1,
        'ajax_page_state[js][sites/all/themes/bcv_ultimate/js/indicadores.js]': 1,
        'ajax_page_state[js][sites/all/themes/bootstrap/js/modules/views/js/ajax_view.js]': 1,
        'ajax_page_state[js][sites/all/themes/bootstrap/js/misc/ajax.js]': 1,
        'ajax_page_state[jquery_version]': '1.10'}

    website = 'https://www.bcv.org.ve/tasas-informativas-sistema-bancario'
    result = requests.get(website, params=payload).text
    soup = BeautifulSoup(result, 'lxml')
    soup = soup.find('div', class_='view-content')
    soup = soup.find('tbody')
    banco = soup.find_all('td', 'views-field views-field-views-conditional')
    compra = soup.find_all('td', 'views-field views-field-field-tasa-compra')
    venta = soup.find_all('td', 'views-field views-field-field-tasa-venta')

    lista = []
    x = 0
    for cu in banco:
        lista.append(cu.get_text(strip=True))
        lista.append(compra[x].get_text(strip=True))
        lista.append(venta[x].get_text(strip=True))
        x = x + 1

    return (lista)
